# Pandas란?

In [1]:
print "데이터 분석, 데이터 처리 등을 쉽게 하기 위해 만들어진 python package이다. 보다 안정적으로 대용량 데이터들을 쉽게 처리할 수 있다고도 알려져 있다."

데이터 분석, 데이터 처리 등을 쉽게 하기 위해 만들어진 python package이다. 보다 안정적으로 대용량 데이터들을 쉽게 처리할 수 있다고도 알려져 있다.


## Series

In [2]:
print "Series는 value와 index의 형태를 지니는 Pandas의 자료 구조이다. 아래 그림과 같이 [1,3,5,7]의 값을 가지는 리스트를 Series로 생성하게 되면 (1,3,5,7)이라는 value와 (0,1,2,3)이라는 index가 생성되어 Series라는 형태의 자료 구조를 만든다."

Series는 value와 index의 형태를 지니는 Pandas의 자료 구조이다. 아래 그림과 같이 [1,3,5,7]의 값을 가지는 리스트를 Series로 생성하게 되면 (1,3,5,7)이라는 value와 (0,1,2,3)이라는 index가 생성되어 Series라는 형태의 자료 구조를 만든다.


In [3]:
from pandas import Series, DataFrame
obj = Series([1,3,5,7])
obj

0    1
1    3
2    5
3    7
dtype: int64

In [4]:
obj.values

array([1, 3, 5, 7], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
print "index는 사용자가 직접 생성할 수 있으며, value에 대한 접근은 index를 사용하여 접근한다. Series의 색인은 사용자가 변경하고 싶을 경우 obj.index값을 변경함으로써 언제든지 변경할 수 있다."

index는 사용자가 직접 생성할 수 있으며, value에 대한 접근은 index를 사용하여 접근한다. Series의 색인은 사용자가 변경하고 싶을 경우 obj.index값을 변경함으로써 언제든지 변경할 수 있다.


In [7]:
obj = Series([1,3,5,7], index = ['a', 'b', 'c', 'd'])
obj

a    1
b    3
c    5
d    7
dtype: int64

In [8]:
obj['a'] = 9
obj

a    9
b    3
c    5
d    7
dtype: int64

In [9]:
obj.index = ['first', 'second', 'third', 'forth']
obj

first     9
second    3
third     5
forth     7
dtype: int64

In [10]:
print "또한 dictionary 형을 Series 형태로 바꾸는 것도 가능하다."

또한 dictionary 형을 Series 형태로 바꾸는 것도 가능하다.


In [11]:
dic = {'first' : 10000, 'second' : 20000, 'third' : 30000, 'forth' : 40000}
obj = Series(dic)
obj

first     10000
forth     40000
second    20000
third     30000
dtype: int64

In [45]:
import pandas as pd

s = pd.Series([4,7,-5,3])
s

0    4
1    7
2   -5
3    3
dtype: int64

In [46]:
s.values

array([ 4,  7, -5,  3], dtype=int64)

In [47]:
s.index

RangeIndex(start=0, stop=4, step=1)

# Vectorized Operation

In [48]:
s * 2

0     8
1    14
2   -10
3     6
dtype: int64

In [49]:
np.exp(s)

0      54.598150
1    1096.633158
2       0.006738
3      20.085537
dtype: float64

# 명시적인 index를 가지는 Series
 
 * 생성시 index 인수로 Index지정
 * Index 원소는 각 데이터에 대한 key 역할을 하는 Label
 * dict

In [50]:
s2 = pd.Series([4,7,-5,3], index = ["d", "b", "a", "c"])
s2

d    4
b    7
a   -5
c    3
dtype: int64

In [51]:
s2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

# Series Indexing 1 : Label Indexing

 * Single Label
 * Label Slicing 
  - 마지막 원소 포함
 * Label을 원소로 가지는 Label (Label을 사용한 List Fancy Indexing)
  - 주어진 순서대로 재배열

In [52]:
s2['a']

-5

In [53]:
s2["b" : "c"]

b    7
a   -5
c    3
dtype: int64

In [54]:
s2[['a', 'b']]

a   -5
b    7
dtype: int64

# Series Indexing 2 : 

 * Single Label
 * Integer Slicing
  - 마지막 원소를 포함하지 않는 일반적인 Slicing
 * Integer List Indexing (List Fancy Indexing)
 * Booleam Fancy Indexing

In [57]:
s2[2]

-5

In [58]:
s2[1:4]

b    7
a   -5
c    3
dtype: int64

In [59]:
s2[[2, 1]]

a   -5
b    7
dtype: int64

In [60]:
s2[s2 > 0]

d    4
b    7
c    3
dtype: int64

# dict 연산

In [61]:
"a" in s2, "e" in s2

(True, False)

In [64]:
for k, v in s2.iteritems():
    print (k, v)

('d', 4)
('b', 7)
('a', -5)
('c', 3)


In [65]:
s2["d":"a"]

d    4
b    7
a   -5
dtype: int64

# dict 데이터를 이용한 Series 생성
 * 별도의 index를 지정하면 지정한 자료만으로 생성

In [66]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
s3 = pd.Series(sdata)
s3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [67]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
s4 = pd.Series(sdata, index=states)
s4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [68]:
pd.isnull(s4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [69]:
pd.notnull(s4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [71]:
s4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [72]:
s4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

# Index 기준 연산

In [73]:
print s3.values, s4.values
s3.values + s4.values

[35000 16000 71000  5000] [    nan  35000.  16000.  71000.]


array([    nan,  51000.,  87000.,  76000.])

In [74]:
s3 + s4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

# Index 이름

In [75]:
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [76]:
s4.name = "population"
s4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [77]:
s4.index.name = "state"
s4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

# Index 변경

In [78]:
s

0    4
1    7
2   -5
3    3
dtype: int64

In [79]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [81]:
s.index = ['Bob',  'Steve', 'Jeff', 'Ryan']
s

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

 * Multi-Series
  - 동일한 Row 인덱스를 사용하는 복수 Series
  - Series를 value로 가지는 dict
 * 2차원 행렬
  - DataFrame을 행렬로 생각하면 각 Series는 행렬의 Column의 역할 
 * NumPy Array와 차이점
  - 각 Column(Series)마다 type이 달라도 된다. 
 * Column Index
  - (Row)Index와 Column Index를 가진다. 
  - 각 Column(Series)에 Label 지정 가능
  - (Row)Index와 Column Label을 동시에 사용하여 자료 접근 가능

In [3]:
import pandas as pd

Data = { 'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year' : [2000, 2001, 2002, 2001, 2002], 'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(Data)
df

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [4]:
pd. DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [5]:
df.dtypes

pop      float64
state     object
year       int64
dtype: object

# 명시적인 Column/Row Index를 가지는 DataFrame

In [6]:
df2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index = ['one', 'two', 'three', 'four', 'five'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

# Single Column Access

In [7]:
df["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [8]:
type(df["state"])

pandas.core.series.Series

In [9]:
df.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

# Cloumn Data Update

In [10]:
df2['debt'] = 16.5
df2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [12]:
import numpy as np

df2['debt'] = np.arange(5)
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [13]:
df2['debt'] = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

# Add Column

In [14]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

# Delete Column

In [15]:
del df2['eastern']
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

# inplace 옵션

 * 함수/메소드는 두 가지 종류 
    - 그 객체 자체를 변형
    - 해당 객체는 그대로 두고 변형된 새로운 객체를 출력
    
 * DataFrame 메소드 대부분은 inplace 옵션을 가짐
    - inplace = True 이면 출력을 None으로 하고 객체 자체를 변형
    - inplace = False 이면 객체 자체는 보존하고 변형된 새로운 객체를 출력

In [16]:
x = [3, 6, 1, 4]
sorted(x)

[1, 3, 4, 6]

In [17]:
x

[3, 6, 1, 4]

In [18]:
x.sort()

# drop 메소드를 사용한 Row/Column 삭제
 * del 함수
    - inplace 연산
 * drop 메소드 
    - 삭제된 Series/DataFrame 출력
    - Series는 Row 삭제
    - DataFrame은 axis 인수로 Row/Column 선택
      - axis=0(디폴트): Row
      - axis=1: Column

In [20]:
s = pd. Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
s

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [21]:
s2 = s.drop('c')
s2

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [22]:
s

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [23]:
s.drop(["b", "c"])

a    0.0
d    3.0
e    4.0
dtype: float64

In [24]:
df = pd. DataFrame(np.arange(16).reshape((4,4)), index = ['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
df.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
df.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [27]:
df.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

# Nested dict를 사용한 DataFrame 생성

In [28]:
pop = { 'Nevada' : {2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7,2002:3.6}}

In [29]:
df3 = pd.DataFrame(pop)
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

# DataFrame의 Column Indexing
 * Single Label key
 * Single Label attribute
 * Label List Fancy Indexing

In [30]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [31]:
df2["year"]

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [33]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [12]:
print "DataFrame은 여러 개의 Dictionary를 처리하는데 있어 Series보다 보기 편한 형태로 제공해 줄 수 있는 자료 구조라고 보면 될 것 같습니다. 마치 엑셀의 표 모양을 생각하면 쉽습니다."

DataFrame은 여러 개의 Dictionary를 처리하는데 있어 Series보다 보기 편한 형태로 제공해 줄 수 있는 자료 구조라고 보면 될 것 같습니다. 마치 엑셀의 표 모양을 생각하면 쉽습니다.


In [13]:
dic = {'state':['Seoul', 'Busan', 'Pohang', 'Gimhae'], 'year' : [2012, 2013, 2014, 2015]}
frame = DataFrame(dic)
frame

state  year
0   Seoul  2012
1   Busan  2013
2  Pohang  2014
3  Gimhae  2015

In [14]:
obj = Series(dic)
obj

state    [Seoul, Busan, Pohang, Gimhae]
year           [2012, 2013, 2014, 2015]
dtype: object

In [15]:
print "위의 그림은 dic이라는 자료애 댜햐 각각 DataFrame과 Series로 그 형태를 나타내 본 것이다. DataFrame형태가 데이터를 보는데 있어 일목요연하게 잘 나타내고 있다. 각 행의 column 명을 배열 index로 기입함으로써 DaraFrame의 값을 가져올 수 있으며, 만약 해당 index로 값을 가져오고 싶다면 ix함수를 이용하면 됩니다."

위의 그림은 dic이라는 자료애 댜햐 각각 DataFrame과 Series로 그 형태를 나타내 본 것이다. DataFrame형태가 데이터를 보는데 있어 일목요연하게 잘 나타내고 있다. 각 행의 column 명을 배열 index로 기입함으로써 DaraFrame의 값을 가져올 수 있으며, 만약 해당 index로 값을 가져오고 싶다면 ix함수를 이용하면 됩니다.


In [16]:
frame.ix[2]

state    Pohang
year       2014
Name: 2, dtype: object

In [17]:
frame['capital'] = frame['state'] == 'Seoul'
frame

state  year capital
0   Seoul  2012    True
1   Busan  2013   False
2  Pohang  2014   False
3  Gimhae  2015   False

In [19]:
del frame ['year']
frame

state capital
0   Seoul    True
1   Busan   False
2  Pohang   False
3  Gimhae   False

# row, column 처리

In [1]:
print "Pandas는 reindex라는 함수를 통해 기존 index를 새롭게 재배치 할 수가 있다. '어?? 분명 Series 공부할 때, obj.index = ['a','b','c','d']이런식으로 index를 다르게 줬었는데 이건 왜 필요하지?? \n\n분명 이전에 obj.index = ['a','b','c','d'] 이런 식으로 index 명칭을 변경했었다. 하지만 이건 재색인 이라기 보다는 그냥 단지 index의 명칭을 기존 명칭에서 ['a','b','c','d']로 바꾼 것 뿐이다. \n\n reindex에 대한 예제 코드를 본다면 위의 기능과 크게 다른 것임을 느끼게 될 것이다. " 

Pandas는 reindex라는 함수를 통해 기존 index를 새롭게 재배치 할 수가 있다. '어?? 분명 Series 공부할 때, obj.index = ['a','b','c','d']이런식으로 index를 다르게 줬었는데 이건 왜 필요하지?? 

분명 이전에 obj.index = ['a','b','c','d'] 이런 식으로 index 명칭을 변경했었다. 하지만 이건 재색인 이라기 보다는 그냥 단지 index의 명칭을 기존 명칭에서 ['a','b','c','d']로 바꾼 것 뿐이다. 

 reindex에 대한 예제 코드를 본다면 위의 기능과 크게 다른 것임을 느끼게 될 것이다. 


In [2]:
from pandas import Series, DataFrame
obj = Series([1,3,5,7], index = ['a','b','c','d'])
obj

a    1
b    3
c    5
d    7
dtype: int64

In [3]:
print "reindex를 통해 index에 해당하는 값들이 재배치된 것을 확인할 수 있을 것이다. 또한 index에 해당하는 값이 없다면 NaN을 나타내준다. reindex시 fill_value의 설정을 통해 NaN 대신 fill_value로 설정한 값을 뿌려줄수가 있다."

reindex를 통해 index에 해당하는 값들이 재배치된 것을 확인할 수 있을 것이다. 또한 index에 해당하는 값이 없다면 NaN을 나타내준다. reindex시 fill_value의 설정을 통해 NaN 대신 fill_value로 설정한 값을 뿌려줄수가 있다.


In [4]:
obj2 = obj.reindex(['e','d','c','b','a'])
obj2

e    NaN
d    7.0
c    5.0
b    3.0
a    1.0
dtype: float64

In [5]:
print "reindex를 통해 index에 해당하는 값들이 재배치된 것을 확인할 수 있을 것이다. 또한 index에 해당하는 값이 없다면 NaN을 나타내준다. reindex시 fill_value의 설정을 통해 NaN 대신 fill_value로 설정한 값을 뿌려줄 수가 있다."

reindex를 통해 index에 해당하는 값들이 재배치된 것을 확인할 수 있을 것이다. 또한 index에 해당하는 값이 없다면 NaN을 나타내준다. reindex시 fill_value의 설정을 통해 NaN 대신 fill_value로 설정한 값을 뿌려줄 수가 있다.


In [6]:
obj2 = obj.reindex(['e','d','c','b','a'], fill_value = 11111)
obj2

e    11111
d        7
c        5
b        3
a        1
dtype: int64

In [7]:
print "DataFrame에도 동일하게 동작한다. columns란 옵션을 통해서 column에 대한 재색인도 할 수 있다."

DataFrame에도 동일하게 동작한다. columns란 옵션을 통해서 column에 대한 재색인도 할 수 있다.


In [8]:
dic = {'state' : ['Seoul', 'Busan', 'Pohand', 'Gimhae'], 'year' : [2012, 2013, 2014, 2015]}
frame = DataFrame(dic, index = ['a','b','c','d'])
frame

state  year
a   Seoul  2012
b   Busan  2013
c  Pohand  2014
d  Gimhae  2015

In [9]:
new_frame = frame.reindex(index=['e','d','c','b','a'], columns = ['state', 'year', 'reserved'])
new_frame

state    year  reserved
e     NaN     NaN       NaN
d  Gimhae  2015.0       NaN
c  Pohand  2014.0       NaN
b   Busan  2013.0       NaN
a   Seoul  2012.0       NaN

# Row, Column 삭제하기

In [10]:
print "drop 함수를 이용하여 해당 데이터의 row나 column을 삭제한다. axis에 1을 줘서 column을 삭제할 수도 있다. row를 삭제하고 싶을 때는 index list를 입력변수로 넣는다. "

drop 함수를 이용하여 해당 데이터의 row나 column을 삭제한다. axis에 1을 줘서 column을 삭제할 수도 있다. row를 삭제하고 싶을 때는 index list를 입력변수로 넣는다. 


In [11]:
new_frame.drop(['c','a'])

state    year  reserved
e     NaN     NaN       NaN
d  Gimhae  2015.0       NaN
b   Busan  2013.0       NaN

In [12]:
new_frame.drop(['reserved'], axis=1)

state    year
e     NaN     NaN
d  Gimhae  2015.0
c  Pohand  2014.0
b   Busan  2013.0
a   Seoul  2012.0

# Pandas 산술 연산

### DataFrame 간의 연산

In [13]:
print "DataFrame간 연산을 하려면 그냥 연산자와 함께 입력해주면 된다."

DataFrame간 연산을 하려면 그냥 연산자와 함께 입력해주면 된다.


In [15]:
import numpy as np

dataFrame1 = DataFrame(np.array([[1,2,3], [2,3,4], [3,4,5]]), columns = list('abc'), index = ['apple', 'banana', 'orange'])
dataFrame1

a  b  c
apple   1  2  3
banana  2  3  4
orange  3  4  5

In [18]:
import numpy as np

dataFrame2 = DataFrame(np.array([[10,11,12,13], [20,21,22,23], [30,31,32,33], [40,41,42,43]]), columns = list('abcd'), index = ['apple', 'banana', 'orange', 'pineapple'])
dataFrame2

a   b   c   d
apple      10  11  12  13
banana     20  21  22  23
orange     30  31  32  33
pineapple  40  41  42  43

In [19]:
dataFrame1 + dataFrame2

a     b     c   d
apple      11.0  13.0  15.0 NaN
banana     22.0  24.0  26.0 NaN
orange     33.0  35.0  37.0 NaN
pineapple   NaN   NaN   NaN NaN

In [20]:
print "위의 그림에서 보면 ['apple', 'banana', 'orange']인덱스를 가진 dataFrame과 ['apple', 'banana', 'orange', 'egg'] 인덱스를 가진 dataFrame 간의 덧셈 연산을 수행하였다. index가 존재하여 연산할 수 없을 경우에는 NaN으로 표시되는 것을 확인할 수 있다. 또한 Column이 존재하지 않은 때도 NaN표시가 나타난다. 덧셈 연산에 add라는 함수를 이용한 후, option으로 fill_value를 지정해 주면 NaN 대신 지정한 값이 표시된다."

위의 그림에서 보면 ['apple', 'banana', 'orange']인덱스를 가진 dataFrame과 ['apple', 'banana', 'orange', 'egg'] 인덱스를 가진 dataFrame 간의 덧셈 연산을 수행하였다. index가 존재하여 연산할 수 없을 경우에는 NaN으로 표시되는 것을 확인할 수 있다. 또한 Column이 존재하지 않은 때도 NaN표시가 나타난다. 덧셈 연산에 add라는 함수를 이용한 후, option으로 fill_value를 지정해 주면 NaN 대신 지정한 값이 표시된다.


In [23]:
dataFrame2.add(dataFrame1, fill_value=0)

a     b     c     d
apple      11.0  13.0  15.0  13.0
banana     22.0  24.0  26.0  23.0
orange     33.0  35.0  37.0  33.0
pineapple  40.0  41.0  42.0  43.0

In [24]:
print "위 그림에서 보면 fill_value를 0으로 지정해주었기 때문에 orange 같은 경우 0 + 33이 되기 때문에 33 값을 나타낸다."

위 그림에서 보면 fill_value를 0으로 지정해주었기 때문에 orange 같은 경우 0 + 33이 되기 때문에 33 값을 나타낸다.


# Pandas 함수들

## ABS

In [26]:
print "각 요소의 절대값을 나타내 준다."

각 요소의 절대값을 나타내 준다.


In [27]:
frame = DataFrame(np.random.randn(4,3), columns=list('bod'), index = ['apple', 'banana', 'egg', 'orange'])
frame

b         o         d
apple  -2.302208  0.216084  0.946630
banana -0.136181  0.817415  2.617151
egg     0.178720 -1.564962 -0.730374
orange  1.630228 -0.474000 -1.992796

In [28]:
np.abs(frame)

b         o         d
apple   2.302208  0.216084  0.946630
banana  0.136181  0.817415  2.617151
egg     0.178720  1.564962  0.730374
orange  1.630228  0.474000  1.992796

## APPLY

In [29]:
print "각 열이나 행 전체를 파라미터로 전달하고 결과를 리턴받는다."

각 열이나 행 전체를 파라미터로 전달하고 결과를 리턴받는다.


In [33]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    3.932436
o    2.382377
d    4.609947
dtype: float64

In [34]:
frame.apply(f, axis=1)

apple     3.248838
banana    2.753332
egg       1.743682
orange    3.623024
dtype: float64

In [35]:
print "위의 첫번째는 b,c,d 각각의 열을 파라미터로 받아 max - min을 진행한 결과이다. \n\n열이나 행이 아니라 각 요소에 적용하고 싶다면 applymap을 이용한다."

위의 첫번째는 b,c,d 각각의 열을 파라미터로 받아 max - min을 진행한 결과이다. 

열이나 행이 아니라 각 요소에 적용하고 싶다면 applymap을 이용한다.


In [37]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      o      d
apple   -2.30   0.22   0.95
banana  -0.14   0.82   2.62
egg      0.18  -1.56  -0.73
orange   1.63  -0.47  -1.99

### 정렬

In [40]:
frame = DataFrame(np.random.randn(4,3), columns = list('dcb'), index = ['banana', 'egg', 'apple', 'orange'])
frame

d         c         b
banana -1.886490  1.042122 -0.302336
egg    -1.484294  0.592685  1.384231
apple   0.743657 -2.080254 -0.813452
orange -0.380518  0.982101  1.169682

In [41]:
frame.sort_index()

d         c         b
apple   0.743657 -2.080254 -0.813452
banana -1.886490  1.042122 -0.302336
egg    -1.484294  0.592685  1.384231
orange -0.380518  0.982101  1.169682

In [42]:
frame.sort_index(axis=1)

b         c         d
banana -0.302336  1.042122 -1.886490
egg     1.384231  0.592685 -1.484294
apple  -0.813452 -2.080254  0.743657
orange  1.169682  0.982101 -0.380518

In [43]:
print "기본적으로 sort_index를 하면 index에 대해 정렬이 되고, axis=1로 설정할 경우 column에 대해서 정렬이 된다. \n\n sort_index의 파라미터로 ascending=False를 줘서 내림차순으로 정렬할 수도 있다.(기본은 오름차순)"

기본적으로 sort_index를 하면 index에 대해 정렬이 되고, axis=1로 설정할 경우 column에 대해서 정렬이 된다. 

 sort_index의 파라미터로 ascending=False를 줘서 내림차순으로 정렬할 수도 있다.(기본은 오름차순)
