In [6]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
print type(a) # 데이터의 형태를 알려줌

print type(1)
print type(1.0)


<type 'numpy.ndarray'>
<type 'int'>
<type 'float'>


In [2]:
L = [0,1,2,3,4,5,6,7,8,9]
print type(L)

<type 'list'>


In [7]:
import numpy as np
data = [1, 2, 3, 4, 5]
arr = np.array(data)
print arr

[1 2 3 4 5]


In [8]:
a = np.arange(1000)
%time a2 = a**2 # %time 은 시스템 속도 나타내줌

Wall time: 0 ns


In [18]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a[0, 1:3]

array([1, 2])

In [20]:
a[1, 1:3]

array([5, 6])

In [21]:
a[2, 1:]

array([ 9, 10, 11])

In [23]:
a[-1, -3:]

array([ 9, 10, 11])

In [28]:
a[:,0]

array([0, 4, 8])

In [29]:
a[:2,1]

array([1, 5])

In [34]:
a[:3, 3]

array([ 3,  7, 11])

In [35]:
a[1:, 3]

array([ 7, 11])

In [36]:
a[-2:, -1]

array([ 7, 11])

In [39]:
a[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [40]:
a[-2:, -3:-1]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
a[0:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [45]:
b = np.arange(60).reshape(3,4,5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [47]:
b[0, :, :] # [ 층(0, 1,2 층), 행, 열]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
b[1, 2:, 3:]

array([[33, 34],
       [38, 39]])

In [49]:
b[1, 1:3, 2:4]

array([[27, 28],
       [32, 33]])

In [54]:
b[0:2, :2, 4]


array([[ 4,  9],
       [24, 29]])

In [55]:
b[:2, :2, -1]

array([[ 4,  9],
       [24, 29]])

In [56]:
b[1:, 1:3, 1:3]

array([[[26, 27],
        [31, 32]],

       [[46, 47],
        [51, 52]]])

In [81]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array(True, False, True, False, True, False, True, False, True, False)

ValueError: only 2 non-keyword arguments accepted

In [83]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[3]

3

In [85]:
i = 3
a[i]

3

In [86]:
a[np.array([True, False, True, False])]

c:\python27\lib\site-packages\ipykernel\__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 4
  if __name__ == '__main__':


array([0, 2])

In [87]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [88]:
a < 5 # a가 5보다 작으면 True, 크면 False

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [89]:
a <= 5 # 5까지 True

array([ True,  True,  True,  True,  True,  True, False, False, False, False], dtype=bool)

In [90]:
a[a<= 5] # 5보다 작은 애들이 뽑혀나온거

array([0, 1, 2, 3, 4, 5])

In [91]:
a % 2  # 모듈(%)로 연산

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [92]:
(a % 2) == 0 # 짝수만(2로 나눈 나머지가 0일때만)

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

In [93]:
a[(a % 2) == 0]

array([0, 2, 4, 6, 8])

In [94]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [95]:
a[(a % 3) == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [96]:
a[(( a % 3 ) == 0) &  (( a % 4) == 1)]

array([ 9, 21, 33, 45, 57, 69, 81, 93])

In [97]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) * 10
idx = np.array([0, 2, 4, 6, 8]) 
a[idx]

# 홀수번째 원소만 골라내려면  (불리안 방식 행렬)

array([ 0, 20, 40, 60, 80])

In [101]:
a = np.array([0, 1, 2, 3]) * 10 # 같은 형태만 들어갈 수 있음
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3])
a[idx]

# 0번째 값, 1번째 값, 2번째 값 (위치 지정 방식 행렬)

array([ 0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 30,
       30, 30])

# NumPy의 자료형

In [102]:
np.array([1, 2, 3])

array([1, 2, 3])

In [106]:
np.array([1, 2, 3.14])

# 정수가 아닌 실수가 나온다. (모두 같은 타입여야하는데 3.14 한놈이 실수이므로)

array([ 1.  ,  2.  ,  3.14])

# i 정수 , f 실수, b 참 혹은 거짓

In [113]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [118]:
np.array([-1, 1, 0]) / np.array ([1, 0, 0])

c:\python27\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([-1,  0,  0])

In [121]:
a = np.zeros(5) 
a

# 크리가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros명령을 사용한다. 


array([ 0.,  0.,  0.,  0.,  0.])

In [122]:
b = np.zeros((5,2), dtype="f8")
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [128]:
c = np.zeros(5, dtype="S4")
c[0] = "abcd"
c[1] = "ABCDE"
c

# 문자열을 잡으면 빈 문자열이 들어간다, 문자열 크기를 반드시 지정해줘야한다
# 4글자 배열인데 5글자 입력하면 잘린다

array(['abcd', 'ABCD', '', '', ''], 
      dtype='|S4')

In [129]:
d = np.ones((2,3,4), dtype="i8")
d

# zeros는 0을 채우고 ones는 1을 채운다

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [131]:
e = range(10)
print(e)
f = np.ones_like(e, dtype="f")
f
# '크기를 튜플(tuple)로 명시하지 않고 특정한 배열 혹은 리스트와 같은 크기의 
#  배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다'

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [133]:
g = np.empty((4,3))
g

# 배열의 크기가 커지면 배열을 초기화하는데 시간이 걸린다. 
# 청소안한 방을 그대로 쓰느냐 청소한 방을 쓰느냐에따라 empty와 zeros가 쓰인다.

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [134]:
np.arange(3, 21, 2)  # start, end (exclusive), step

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [135]:
np.arange(1, 21, 5)

array([ 1,  6, 11, 16])

In [138]:
np.linspace(0, 100, 5)  # start, end, num-points

# 시작 숫자, 100이하, 5개(25단위)

array([   0.,   25.,   50.,   75.,  100.])

In [139]:
np.linspace(0, 10, 6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

In [140]:
np.logspace(0, 4, 4, endpoint=False)

# 지수함수적으로 나간다

array([    1.,    10.,   100.,  1000.])

In [163]:
np.random.seed(0)

# seed가 바뀌면 밑의 rand 넘버 값도 바뀐다.

In [164]:
np.random.rand(4)

# ctrl + enter 를 치면 숫자가 랜덤으로 바뀐다

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318])

In [165]:
np.random.randn(3,5)

array([[ 1.86755799, -0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826,  0.3130677 ]])

In [166]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [167]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
c = np.arange(35)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [172]:
d = c.reshape(5, 7)
d

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [173]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [174]:
y = x.reshape(5,1)
y

# 2차원 array다 

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [176]:
z = x[:, np.newaxis]
z

# 2차원으로 만드는 방법은 reshape과 newaxis 두가지 방법이 있다

array([[0],
       [1],
       [2],
       [3],
       [4]])

# hstack 행렬 옆으로 늘림
# vstack 행렬 밑으로 붙음

In [177]:
a1 = np.ones((2, 3))
a1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [178]:
a2 = np.zeros((2, 2))
a2

array([[ 0.,  0.],
       [ 0.,  0.]])

In [179]:
np.hstack([a1, a2])

array([[ 1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.]])

In [180]:
a1 = np.ones((2, 2))
a1

array([[ 1.,  1.],
       [ 1.,  1.]])

In [182]:
np.hstack([a1 * 1, a1 * 2, a2 * 3])

array([[ 1.,  1.,  2.,  2.,  0.,  0.],
       [ 1.,  1.,  2.,  2.,  0.,  0.]])

In [187]:
np.arange(1, 4).reshape(3, 1)

array([[1],
       [2],
       [3]])

In [189]:
b1 = np.ones((2, 3))
b1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [190]:
b2 = np.zeros((3, 3))
b2

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [192]:
x = np.arange(-4, 5)
x

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [193]:
np.vstack([x, x, x, x, x, x])

array([[-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [199]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [200]:
X, Y = np.meshgrid(x, y)

In [201]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [202]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [204]:
x = np.arange(-4, 5)
x

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

# NumPy 연산

In [207]:
x = np.arange(1, 101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [208]:
y = np.arange(101, 201)
y

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199, 200])

In [209]:
%%time
z = np.zeros_like(x)
for i, (xi, yi) in enumerate(zip(x, y)):
    z[i] = xi + yi

Wall time: 1e+03 µs


In [210]:
z

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204,
       206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
       232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,
       258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282,
       284, 286, 288, 290, 292, 294, 296, 298, 300])

In [211]:
%%time
z = x + y

Wall time: 0 ns


In [212]:
z

array([102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204,
       206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
       232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256,
       258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282,
       284, 286, 288, 290, 292, 294, 296, 298, 300])

# 브로드캐스팅

In [213]:
x = np.arange(5)
y = np.ones_like(x)
x + y

array([1, 2, 3, 4, 5])

In [214]:
x + 1

array([1, 2, 3, 4, 5])

In [215]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [216]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [217]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [218]:
a = np.arange(0, 40, 10)[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [219]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

#  차원 축소 연산

## min : 최소값 찾기
## max : 최대값 (1등한 애)
## argmin : 성적이 중요한게 아니고 꼴등한애 나와, 누가 꼴등이냐, 꼴등이 몇번째앤지


In [220]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [221]:
np.sum(x)

10

In [222]:
x.sum()

10

In [223]:
x = np.array([1, 3, 2])

In [224]:
x.min()

1

In [225]:
x.max()

3

In [226]:
x.argmin()  # 몇번째 애가 꼴등인지, 인덱스 넘버는 0이다. 

0

In [227]:
x.argmax()  # 1등한애 위치, 따라서 인덱스 1


1

In [228]:
x = np.array([1, 2, 3, 1])

In [229]:
x.mean()

1.75

In [230]:
np.median(x)

1.5

In [231]:
np.all([True, True, False]) 

False

In [233]:
np.any([True, True, False]) # 하나라도 True가 있음 True

True

In [234]:
a = b = np.arange(10)

In [235]:
np.array_equal(a, b)

True

In [236]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [237]:
x.sum()

6

In [239]:
x.sum(axis=0)   # 0번 축을 없애라(행이 없어진다, 위아래로 찌그러뜨린다) 

array([3, 3])

In [241]:
x.sum(axis=1)   # 열을 없애라, 양옆으로 찌그러짐 (axis의 숫자는 내가 없애려는 차원의 인덱스 넘버)

array([2, 4])

In [242]:
y = np.array([[1, 2, 3], [5, 6, 1]])
np.median(y, axis=-1) # last axis

array([ 2.,  5.])

# 정렬

In [243]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [244]:
np.sort(a)

array([[3, 4, 5],
       [1, 1, 2]])

In [246]:
np.sort(a, axis=1) # ???

array([[3, 4, 5],
       [1, 1, 2]])

In [247]:
np.sort(a, axis=0) # ???

array([[1, 2, 1],
       [4, 3, 5]])

In [249]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j
# 제일 꼴지에서 몇번째 위치인지
# 1등의 위치는 맨 뒤에있는 애로 나타내준다. . 
# in-place는 무엇인가?????

array([2, 3, 1, 0])

In [250]:
a[j]

array([1, 2, 3, 4])

In [253]:
np.argsort(-1)

array([0])

# NumPy를 활용한 선형대수 입문

In [254]:
# R은 리얼넘버다

In [255]:
# 벡터는 위에서 아래로 쓰는데 기본적으로 일차원 어레이로 옆으로 나타내도 된다.

In [256]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [257]:
x = np.array([[1], [2], [3], [4]])
x

array([[1],
       [2],
       [3],
       [4]])

# 행렬

In [259]:
X = np.array([[11,12,13],[21,22,23]])
X


array([[11, 12, 13],
       [21, 22, 23]])

# 특수한 행렬

In [260]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [261]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [262]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# 연산

In [263]:
# 행렬은 나누기는 없고 곱하기는 여러개다 

# 전치 연산

In [264]:
# 행이 열이되고 열이 행이된다


In [265]:
X = np.array([[11,12,13],[21,22,23]])
X

array([[11, 12, 13],
       [21, 22, 23]])

In [266]:
X.T

array([[11, 21],
       [12, 22],
       [13, 23]])

# 벡터 곱셈

In [267]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.dot(x, y)

32

# 행렬의 곱셈

In [268]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.dot(A, B)

In [269]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [272]:
C

array([[22, 28],
       [49, 64]])

# 가중 벡터합은 수식에 익숙해져야 한다