# NumPy 란?

In [1]:
print "Numerical Python의 줄임 말로써 고성능의 수치 계산을 하기 위해 만들어진 python package이다. 파이썬을 이용한 데이터 분석을 하기 위해서는 pandas 뿐만 아니라 numpy를 익혀야만 보다 효율적인 데이터 분석이 가능하다."

Numerical Python의 줄임 말로써 고성능의 수치 계산을 하기 위해 만들어진 python package이다. 파이썬을 이용한 데이터 분석을 하기 위해서는 pandas 뿐만 아니라 numpy를 익혀야만 보다 효율적인 데이터 분석이 가능하다.


In [1]:
print "데이터는 수많은 숫자들로 이루어져 있다. 이 많은 숫자들을 효율적으로 계산하기 위해서는 관련된 데이터를 모두 하나의 변수에 넣고 처리해야 한다. 하나의 변수에 여러 개의 데이터를 넣는 방법으로 리스트를 사용할 수도 있지만 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 더 적은 메모리를 사용해서 빠르게 데이터를 처리하려면 배열(array)을 사용해야 한다. \n\n 배열은 같은 자료형의 데이터를 정해진 갯수만큼 모아놓은 것이다. 배열은 다음과 같은 점에서 리스트와 다르다. \n\n 1. 모든 원소가 같은 자료형이어야 한다. \n\n 2. 원소의 갯수를 바꿀 수 없다. \n\n 파이썬은 자체적으로 배열 자료형을 제공하지 않는다. 따라서 배열을 구현한 다른 패키지를 임포트해야 한다. 파이썬에서 배열을 사용하기 위한 표준 패키지는 NumPy이다."

데이터는 수많은 숫자들로 이루어져 있다. 이 많은 숫자들을 효율적으로 계산하기 위해서는 관련된 데이터를 모두 하나의 변수에 넣고 처리해야 한다. 하나의 변수에 여러 개의 데이터를 넣는 방법으로 리스트를 사용할 수도 있지만 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 더 적은 메모리를 사용해서 빠르게 데이터를 처리하려면 배열(array)을 사용해야 한다. 

 배열은 같은 자료형의 데이터를 정해진 갯수만큼 모아놓은 것이다. 배열은 다음과 같은 점에서 리스트와 다르다. 

 1. 모든 원소가 같은 자료형이어야 한다. 

 2. 원소의 갯수를 바꿀 수 없다. 

 파이썬은 자체적으로 배열 자료형을 제공하지 않는다. 따라서 배열을 구현한 다른 패키지를 임포트해야 한다. 파이썬에서 배열을 사용하기 위한 표준 패키지는 NumPy이다.


In [2]:
print "NumPy는 2005년에 Travis Oliphant가 발표한 수치해석용 Python 패키지이다. 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다. 내부적으로는 BLAS 라이브러리와 LAPACK 라이브러리에 기반하고 있어서 C로 구현된 CPython에서만 사용할 수 있다. \n\n NumPy의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 Python 반복문에 비해 속도가 빠르며 벡터화 연산(vectorized operation)을 사용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다. 또한 배열 인덱싱(array indexing)을 사용한 질의(Query)기능을 이용하여 짧고 간단한 코드로 복잡한 수식을 계산할 수 있다. "

NumPy는 2005년에 Travis Oliphant가 발표한 수치해석용 Python 패키지이다. 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다. 내부적으로는 BLAS 라이브러리와 LAPACK 라이브러리에 기반하고 있어서 C로 구현된 CPython에서만 사용할 수 있다. 

 NumPy의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 Python 반복문에 비해 속도가 빠르며 벡터화 연산(vectorized operation)을 사용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다. 또한 배열 인덱싱(array indexing)을 사용한 질의(Query)기능을 이용하여 짧고 간단한 코드로 복잡한 수식을 계산할 수 있다. 


* NumPy
 + 수치해석용 Python 라이브러리
 + ndarray 다차원 배열 자료 클래스 제공
 + BLAS/LAPACK 기반
 + CPython에서만 사용 가능
 + 내부 반복문 사용으로 빠른 배열 연산 가능
 + 배열 인덱싱(array indexing)을 사용한 질의(Query)기능

# NumPy 패키지 임포트

In [3]:
print "배열을 사용하기 위해서는 우선 다음과 같이 NumPy 패키지를 임포트한다. NumPy는 np라는 이름으로 임포트하는 것이 관례이다. "

배열을 사용하기 위해서는 우선 다음과 같이 NumPy 패키지를 임포트한다. NumPy는 np라는 이름으로 임포트하는 것이 관례이다. 


In [1]:
import numpy as np

# 1차원 배열 만들기 

In [5]:
print "NumPy의 array라는 함수에 리스트를 넣으면 배열로 변환해 준다. 따라서 1차원 배열을 만드는 방법은 다음과 같다."

NumPy의 array라는 함수에 리스트를 넣으면 배열로 변환해 준다. 따라서 1차원 배열을 만드는 방법은 다음과 같다.


In [2]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(a)

numpy.ndarray

In [8]:
print "만들어진 ndarray 객체의 표현식 (representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐 리스트와 동일한 구조처럼 보인다. 그러나 배열 객체와 리스트 객체는 많은 차이가 있다. \n\n 우선 리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 이러한 제약을 가지는 대신 내부의 원소에 대한 점근과 반복문 실행이 빨라진다."

만들어진 ndarray 객체의 표현식 (representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐 리스트와 동일한 구조처럼 보인다. 그러나 배열 객체와 리스트 객체는 많은 차이가 있다. 

 우선 리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 이러한 제약을 가지는 대신 내부의 원소에 대한 점근과 반복문 실행이 빨라진다.


# 벡터화 연산

In [9]:
print "배열 객체는 배열의 각 원소에 대한 연산을 한 번에 처리하는 벡터화 연산(vectorized operation)을 지원한다는 점이다."

배열 객체는 배열의 각 원소에 대한 연산을 한 번에 처리하는 벡터화 연산(vectorized operation)을 지원한다는 점이다.


In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [7]:
2 * a + b

array([12, 24, 36])

In [8]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [9]:
np.log(b)

array([ 2.30258509,  2.99573227,  3.40119738])

# 2차원 배열 만들기 

In [14]:
print "ndarray는 N-dimensional-Array의 약자이다. 이름 그대로 배열 객체는 단순 리스트와 유사한 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원한다. \n\n 2차원 배열은 행렬(matrix)이라고도 하는데 행렬에서는 가로줄을 행(row)이라고 하고 세로줄을 열(column)이라고 한다. \n\n다음과 같이 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있다. 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기가 된다. 예를 들어 2 x 3 배열은 다음과 같이 만든다."

ndarray는 N-dimensional-Array의 약자이다. 이름 그대로 배열 객체는 단순 리스트와 유사한 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원한다. 

 2차원 배열은 행렬(matrix)이라고도 하는데 행렬에서는 가로줄을 행(row)이라고 하고 세로줄을 열(column)이라고 한다. 

다음과 같이 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있다. 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기가 된다. 예를 들어 2 x 3 배열은 다음과 같이 만든다.


In [15]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
len(b)

2

In [17]:
len(b[0])

3

# 3차원 배열 만들기

In [18]:
print "리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있다. 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트의 길이 순서대로 표시한다. 예를 들어 2 x 3 x 4 배열은 다음과 같이 만든다."

리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있다. 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트의 길이 순서대로 표시한다. 예를 들어 2 x 3 x 4 배열은 다음과 같이 만든다.


In [19]:
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

# 배열의 차원과 크기 알아내기 
 - 배열의 차원 및 크기는 ndim 속성과 shape 속성으로 알 수 있다.

In [20]:
print a.ndim
print a.shape

1
(3,)


In [21]:
print b.ndim
print b.shape

2
(2, 3)


In [22]:
print c.ndim
print c.shape

3
(2, 3, 4)


# 배열의 인덱싱
 - 배열 객체로 구현한 다차원 배열의 원소 하나 하나는 다음과 같이 콤마(comma ,)를 사용하여 접근할 수 있다. 콤마로 구분된 차원을 축(axis)이라고도 한다. 플롯의 x축과 y축을 떠올리면 될 것이다. 

In [23]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
a[0,0] # 첫 번째 행의 첫번째 열

0

In [25]:
a[0,1] #첫 번째 행의 두번째 열

1

In [26]:
a[-1, -1] # 마지막 행의 마지막 열

5

# 배열 슬라이싱 
 - 배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용하면 된다.      

In [28]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [30]:
a[:, 1] # 두번째 열 전체

array([1, 5])

In [31]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [32]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

#배열 인덱싱 
 - NumPy 배열 객체의 또 다른 강력한 기능은 팬시 인덱싱(fancy indexing)이라고도 부르는 배열 인덱싱(array indexing)방법이다. 인덱싱이라는 이름이 붙었지만 사실은 데이터베이스의 질의(Query) 기능을 수행한다. 
 
 배열 인덱싱에서는 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray 배열을 받을 수 있다. 여기에서는 이 배열을 편의상 인덱스 배열이라고 부르겠다. 배열 인덱싱의 방식에는 불리안(Boolean) 배열 방식과 정수 배열 방식 두가지가 있다. 
 
 먼저 불리안 배열 인덱싱 방식은 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 한다. 
 
 예를 들어 다음과 같은 1차원 ndarray에서 홀수인 원소만 골라내려면 홀수인 원소에 대응하는 인덱스 값이 True이고 짝수인 원소에 대응하는 인덱스 값이 False인 인덱스 배열을 넣으면 된다. 

In [35]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [37]:
a[a % 2 == 0] # 조건문 연산을 사용하면 다음과 같이 간단하게 쓸 수 있다.

array([0, 2, 4, 6, 8])

* 정수 배열 인덱싱에서는 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수이여야 한다. 예를 들어 1차원 배열에서 홀수번째 원소만 골라내는 것은 다음과 같다

In [38]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) * 10
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([ 0, 20, 40, 60, 80])

* 배열 인덱싱
 + 불리안(Boolean) 방식 배열 인덱싱
    - True 인 원소만 선택
    - 인덱스의 크기가 배열의 크기와 같아야 한다. 

 + 위치 지정 방식 배열 인덱싱
   - 지정된 위치의 원소만 선택
   - 인덱스의 크기가 배열의 크기와 달라도 된다.

# NumPy 배열 생성과 변형 

## NumPy의 자료형 

 - NumPy의 ndarray 클래스는 포함하는 모든 데이터가 같은 자료형 (data type)이어야 한다. 또한 자료형 자체도 일반 파이썬에서 제공하는 것보다 훨씬 세분화되어 있다. \n\n NumPy의 자료형은 dtype이라는 인수로 지정한다. dtype 인수로 지정할 값은 다음 표에 보인것과 같은 dtype접두사로 시작하는 문자열이고 비트/바이트 수를 의미하는 숫자가 붙을 수도 있다.

In [42]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

# 배열 생성

In [44]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

앞에서 파이썬 리스트를 NumPy의 ndarray 객체로 변환하여 생성하려면 array명령을 사용하였다. 그러나 보통은 이러한 기본 객체없이 다음과 같은 명령을 사용하여 바로 ndarray객체를 생성한다. 
    - zeros, ones
    - zeros_like, ones_like
    - empty
    - arange
    - linspace, logspace
    - rand, randn

크기가 정해져 있고 모든 값이 0 인 배열을 생성하려면 zeros 명령을 사용한다. dtype 인수가 없으면 정수형이 된다.

In [45]:
a = np.zeros(5)
a

array([ 0.,  0.,  0.,  0.,  0.])

dtype 인수를 명시하면 해당 자료형 원소를 가진 배열을 만든다.

In [46]:
b = np.zeros((5, 2), dtype = "f8")
b

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

문자열 배열도 가능해지면 모든 원소의 문자열 크기가 같아야 한다. 만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있다.

In [49]:
c = np.zeros(5, dtype = "S4")
c[0] = "abcd"
c[1] = "ABCDE"
c

array(['abcd', 'ABCD', '', '', ''], 
      dtype='|S4')

1이 아닌 0으로 초기화된 배열을 생성하려면 ones 명령을 사용한다.

In [50]:
d = np.ones((2,3,4), dtype = "i8")
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

만약 크기를 튜플(tuple)로 명시하지 않고 특정한 배열 혹은 리스트와 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다.

In [51]:
e = range(10)
print e

f = np.ones_like(e, dtype = "f")
f

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다. 이 시간을 단축하려면 생성만 하고 초기화를 하지 않는 empty 명령을 사용할 수 있다. empty 명령으로 생성된 배열에 어떤 값이 들어있을지는 알 수 없다. 

In [53]:
g = np.empty((4,3))
g

array([[  2.12199579e-314,   6.36598737e-314,   1.06099790e-313],
       [  1.48539705e-313,   1.90979621e-313,   2.33419537e-313],
       [  2.75859453e-313,   3.18299369e-313,   3.60739285e-313],
       [  4.03179200e-313,   4.45619116e-313,   4.88059032e-313]])

arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다.

In [54]:
np.arange(10) # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(3, 21, 2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [56]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.

In [57]:
np.linspace(0, 100, 5) # 시작, 끝(포함), 갯수

array([   0.,   25.,   50.,   75.,  100.])

In [58]:
np.logspace(0, 4, 4, endpoint=False)

array([    1.,    10.,   100.,  1000.])

임의의 난수를 생성하고 싶다면 random  서브패키지의 rand 혹은 randn 명령을 사용한다. rand 명령을 uniform 분포를 따르는 난수를 생성하고 randn 명령은 가우시안 정규 분포를 따르는 난수를 생성한다. 생성할 시드(seed)값을 지정하려면 seed 명령을 사용한다. 

In [66]:
np.random.seed(2)

In [67]:
np.random.rand(4)

array([ 0.4359949 ,  0.02592623,  0.54966248,  0.43532239])

In [68]:
np.random.randn(3, 5)

array([[-1.79343559, -0.84174737,  0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801,  0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 , -0.0191305 ,  1.17500122, -0.74787095]])

# 배열의 크기 변형
 - 일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용한다. 예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있다.

In [69]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

사용하는 원소의 갯수가 정해져 있기 때문에 reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수있다. -1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용된다.

In [72]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [79]:
a.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [73]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [78]:
a.reshape(2, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

다차원 배열을 무조건 1차원으로 펼치기위해서는 flatten 명령이나 메서드를 사용한다. 

In [80]:
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [81]:
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22])

배열 사용에서 주의할 점은 길이가 5인1차원 배열과 행, 열의 갯수가 (5, 1)인 2차원 배열 또는 행, 열의 갯수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.

In [82]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [83]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [84]:
x. reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 배열 연결 

행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여 (concatenate) 더 큰 배열을 만들 때는 다음과 같은 명령을 사용한다. 

* hstack
* vstack
* dstack
* stack
* r_
* c_
* rile

hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다. 연결할 배열은 하나의 리스트에 담아야 한다. 

In [88]:
a1 = np.ones((2, 3))
a1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [89]:
a2 = np.zeros((2,2))
a2

array([[ 0.,  0.],
       [ 0.,  0.]])

In [92]:
np.hstack([a1, a2])

array([[ 1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.]])

In [93]:
np.hstack([a2, a1])

array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.]])

vstack 명령은 열의 수가 같은 두 개 이상의배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다. 연결할 배열은 마찬가지로 하나의 리스트에 담아야 한다. 

In [94]:
b1 = np.ones((2, 3))
b1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [95]:
b2 = np.zeros((3, 3))
b2

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [96]:
np.vstack([b1, b2])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [97]:
np.vstack([b2, b1])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth)방향으로 배열을 합친다.

In [99]:
c1 = np.ones((2, 3))
c1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [101]:
c2 = np.zeros((2, 3))
c2

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [102]:
np.dstack([c1, c2])

array([[[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]],

       [[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]]])

In [105]:
d1 = np.ones((5, 4))
d1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [106]:
d2 = np.zeros((5, 4))
d2

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [109]:
np.dstack([d1, d2])

array([[[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]],

       [[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]],

       [[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]],

       [[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]],

       [[ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.],
        [ 1.,  0.]]])

stack 명령은 새로운 차원(축으로) 배열을 연결하며 당연히 연결하고자 하는 배열들의 크기가 모두 같아야 한다. axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정한다.

In [110]:
c = np.stack([c1, c2])
c

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

axis 인수는 새로 추가되는 차원을 지정한다. 다음 코드로 확인할 수 있다. 여기에서 array_equal 명령은 배열의 원소가 아니라 배열 전체를 비교하는 명령이다.

In [111]:
np.array_equal(c[0, :, :], c1), np.array_equal(c[1, :, :], c2)

(True, True)

In [112]:
c = np.stack([c1, c2], axis=1)
c

array([[[ 1.,  1.,  1.],
        [ 0.,  0.,  0.]],

       [[ 1.,  1.,  1.],
        [ 0.,  0.,  0.]]])

In [113]:
np.array_equal(c[:, 0, :], c1), np.array_equal(c[:, 1, :], c2)

(True, True)

# 그리드 생성

변수가 2개인 2차원 함수의 그래프를 그리거나 표를 작성하려면 많은 좌표를 한꺼번에 생성하여 각 좌표에 대한 함수 값을 계산해야 한다. 예를 들어 x, y 라는 두 변수를 가진 함수에서 x가 0부터 2까지, y가 0부터 4까지의 사각형 영역에서 변화하는 과정을 보고 싶다면 이 사각형 영역 안의 다음과 같은 (x,y) 쌍 값들에 대해 함수를 계산해야 한다.

(x,y)=(0,0),(0,1),(0,2),(0,3),(0,4),(1,0),⋯(2,4)
(x,y)=(0,0),(0,1),(0,2),(0,3),(0,4),(1,0),⋯(2,4)
 
이러한 과정을 자동으로 해주는 것이 NumPy의 meshgrid 명령이다. meshgrid 명령은 사각형 영역을 구성하는 가로축의 점들과 세로축의 점을 나타내는 두 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합을 출력한다. 단 조합이 된 (x,y)쌍을 x값만을 표시하는 행렬과 y값만을 표시하는 행렬 두 개로 분리하여 출력한다.

In [114]:
x = np.arange(3)
x

array([0, 1, 2])

In [115]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [116]:
X, Y = np.meshgrid(x, y)

In [117]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [118]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [119]:
[zip(x, y) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [121]:
plt.scatter(X, Y, linewidths=10);

# plt 시각 프로그램 안깔림

NameError: name 'plt' is not defined

# ndarray

In [2]:
print "NumPy에서 가장 강력한 무기로 칭송받고 있는 N차원의 배열 객체. ndarray는 기존 파이썬과는 다르게 오직 같은 종류의 데이터만을 배열에 담을 수 있다."

NumPy에서 가장 강력한 무기로 칭송받고 있는 N차원의 배열 객체. ndarray는 기존 파이썬과는 다르게 오직 같은 종류의 데이터만을 배열에 담을 수 있다.


# ndarray의 생성

In [3]:
print "NumPy의 array함수를 통해 쉽게 배열 형태로 만들 수 있다."

NumPy의 array함수를 통해 쉽게 배열 형태로 만들 수 있다.


In [4]:
import numpy as np
data = [1, 2, 3, 4, 5]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [5]:
data = [[1,2,3,4], [5,6,7,8]]
arr = np.array(data)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print "또한 zeros, ones 함수를 통해 0행렬, 또는 모든 행렬 값이 1인 행렬을 만들 수 있다. empty 함수는 행렬 값이 초기화되지 않은 행렬을 생성한다."

또한 zeros, ones 함수를 통해 0행렬, 또는 모든 행렬 값이 1인 행렬을 만들 수 있다. empty 함수는 행렬 값이 초기화되지 않은 행렬을 생성한다.


In [7]:
np.empty((3,3))

array([[  1.06134938e-312,   0.00000000e+000,   1.06395697e+224],
       [  4.98886723e-037,   3.50444305e-033,   1.51824106e-051],
       [  2.79113402e+179,   3.40837919e-085,   3.31326745e-292]])

In [8]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
print "arange 함수를 통해 범위 내의 값을 순차적으로 가지는 배열을 생성할 수 있다."

arange 함수를 통해 범위 내의 값을 순차적으로 가지는 배열을 생성할 수 있다.


In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# ndarray의 차수 및 모양, 타입 확인

In [12]:
print "ndim, shape, dtype 함수를 통해 차수와 배열 모양, 배열의 자료 타입을 확인 할 수 있다."

ndim, shape, dtype 함수를 통해 차수와 배열 모양, 배열의 자료 타입을 확인 할 수 있다.


In [13]:
arr.ndim # 행 수

2

In [14]:
arr.shape # 2행 4열

(2, 4)

In [15]:
arr.dtype

dtype('int32')

# ndarray의 타입 변환

In [16]:
print "astype 함수를 통해 자료 타입의 변환이 가능하다. 아래 그림은 int형 자료형을 float로 변환하는 예제를 보여준다."

astype 함수를 통해 자료 타입의 변환이 가능하다. 아래 그림은 int형 자료형을 float로 변환하는 예제를 보여준다.


In [17]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [18]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [20]:
print "문자열 형태를 정수형으로 변환하는 것도 가능하다."

문자열 형태를 정수형으로 변환하는 것도 가능하다.


In [21]:
arr = np.array(['1','2','3','4','5'])
arr

array(['1', '2', '3', '4', '5'], 
      dtype='|S1')

In [23]:
int_arr = arr.astype(np.int64)
int_arr.dtype

dtype('int64')

In [24]:
int_arr

array([1, 2, 3, 4, 5], dtype=int64)

In [25]:
print "astype을 호출하면 dtype이 같더라도 항상 새로운 배열을 생성하게 된다는 것을 유의하자."

astype을 호출하면 dtype이 같더라도 항상 새로운 배열을 생성하게 된다는 것을 유의하자.


# ndarray 연산

In [26]:
print "ndarray는 아래와 같은 방법으로 연산이 가능하다. ndarray에서의 연산은 for문 연산이 아니기 때문에 일괄처리가 가능하다."

ndarray는 아래와 같은 방법으로 연산이 가능하다. ndarray에서의 연산은 for문 연산이 아니기 때문에 일괄처리가 가능하다.


In [27]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,7,8],[9,19,11]])
arr1 + arr2

array([[ 7,  9, 11],
       [13, 24, 17]])

In [28]:
arr1 * arr2

array([[ 6, 14, 24],
       [36, 95, 66]])

# ndarray 슬라이싱

In [32]:
print "ndarray도 python 문자열이나 list 처럼 슬라이싱이 가능하다. \n\n리스트 슬라이싱과의 중요한 차이점은 리스트의 경우에는 슬라이싱을 할 경우 데이터 복사가 이루어지지만 ndarray 슬라이싱의 경우는 원본 배열은 그대로 저장되어 있고 사용자에게 보여주는 뷰만 다른 형태로 보여주는 것이기 때문에 데이터 복사가 이루어 지지 않는다.\n\n뷰 형태로 보여지더라도 해당 값은 그대로 참조하고 있기 때문에 만약 여기서 arr[:5] = 1이라고 입력하면 arr의 배열 값이 변경되어 array([1,1,1,1,1,5,6,7,8,9])로 바뀌어질 것이다. \n\n참조가 아닌 새로운 배열의 값을 가지고 싶다면 arr[:5].copy()함수를 사용하면 새로운 배열이 만들어 진다."

ndarray도 python 문자열이나 list 처럼 슬라이싱이 가능하다. 

리스트 슬라이싱과의 중요한 차이점은 리스트의 경우에는 슬라이싱을 할 경우 데이터 복사가 이루어지지만 ndarray 슬라이싱의 경우는 원본 배열은 그대로 저장되어 있고 사용자에게 보여주는 뷰만 다른 형태로 보여주는 것이기 때문에 데이터 복사가 이루어 지지 않는다.

뷰 형태로 보여지더라도 해당 값은 그대로 참조하고 있기 때문에 만약 여기서 arr[:5] = 1이라고 입력하면 arr의 배열 값이 변경되어 array([1,1,1,1,1,5,6,7,8,9])로 바뀌어질 것이다. 

참조가 아닌 새로운 배열의 값을 가지고 싶다면 arr[:5].copy()함수를 사용하면 새로운 배열이 만들어 진다.


In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[:5]

array([0, 1, 2, 3, 4])

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr[:1,:1]

array([[1]])

In [37]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [40]:
arr[:1,2]

array([3])

In [53]:
arr = np.array([[1,2,3],[4,5,6]])
arr[:1, :2] = 0
arr

array([[0, 0, 3],
       [4, 5, 6]])

# ndarray 색인

In [54]:
print "1차원 배열에서의 색인은 리스트 색인과 비슷하다. "

1차원 배열에서의 색인은 리스트 색인과 비슷하다. 


In [56]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr[3]

3

In [58]:
print "다차원 배열에서의 색인 결과는 1차원 배열 형태로 리턴된다. 만약 개별 원소 하나의 값을 얻고자 한다면 해당 원소의 index를 명확하게 넘겨주어야 한다."

다차원 배열에서의 색인 결과는 1차원 배열 형태로 리턴된다. 만약 개별 원소 하나의 값을 얻고자 한다면 해당 원소의 index를 명확하게 넘겨주어야 한다.


In [59]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr[5]

5

In [61]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr[1]

array([4, 5, 6])

In [63]:
arr[2,2]

9

# 불리언 색인

In [64]:
print "name이라는 사람 이름을 가지고 있는 배열이 있다고 가정할 때, 어떤 조건을 걸게 되면 각 원소들을 해당 조건과 비교하여 True, False를 리턴하게 된다."

name이라는 사람 이름을 가지고 있는 배열이 있다고 가정할 때, 어떤 조건을 걸게 되면 각 원소들을 해당 조건과 비교하여 True, False를 리턴하게 된다.


In [65]:
name = np.array(['Bob', 'Sam', 'Bob', 'Joy', 'Kebin', 'Joe'])
name == 'Bob'

array([ True, False,  True, False, False, False], dtype=bool)

# 팬시 색인

In [4]:
import numpy as np

In [22]:
data = [[0,0,0,0], [1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4], [5,5,5,5], [6,6,6,6], [7,7,7,7]]
arr = np.array(data)
arr


array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [23]:
arr[[1,3,5,7]]

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [5, 5, 5, 5],
       [7, 7, 7, 7]])

In [24]:
arr[[0,1,2,3,4,5,6,7]]

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

# ndarray 축 바꾸기

In [25]:
print "T라는 속성값을 이용하면 배열의 축을 변경할 수 있다."

T라는 속성값을 이용하면 배열의 축을 변경할 수 있다.


In [27]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [28]:
arr.T

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [29]:
print "배열 축을 바꾸더라도 데이터 복사로 인해 배열이 새로 생기는 것이 아니라 단지 뷰의 형태만 바뀌게 된다."

배열 축을 바꾸더라도 데이터 복사로 인해 배열이 새로 생기는 것이 아니라 단지 뷰의 형태만 바뀌게 된다.
