# 배열의 연산

## 벡터화 연산 

NumPy는 코드를 간단하게 만들고 계산 속도를 빠르게 하기 위한 벡터화 연산을 제원한다. 벡터화 연산이란 반복문(loop)을 사용하지 않고 선형 대수의 벡터 혹은 행렬 연산과 유사한 코드를 사용하는 것을 말한다. 

In [2]:
import numpy as np
import pandas as pd

x = np.arange(1, 1001)
y = np.arange(1001, 2001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range (1000):
    z[i] = x[i] + y[i]

Wall time: 1e+03 µs


In [4]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

비교 연산도 벡터화 연산이 가능하다.

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [6]:
a == b

array([False,  True, False,  True], dtype=bool)

In [7]:
a >=  b

array([False,  True,  True,  True], dtype=bool)

만약 배열 전체를 비교하고 싶다면 all 명령을 사용한다.

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [9]:
np.all(a==b)

False

In [10]:
np.all(a==c)

True

## 스칼라와 벡터/행렬의 곱셈

스칼라와 벡터/행렬의 곱도 선형 대수에서 사용하는 식과 NumPy 코드가 일치한다.

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [15]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])